<a href="https://colab.research.google.com/github/joeytai/Machine-Learning/blob/main/deep_learning_coputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
class MLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.flatten = tf.keras.layers.Flatten()    # Flatten层将除第一维（batch_size）以外的维度展平
        self.dense1 = tf.keras.layers.Dense(units=256, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(units=10)

    def call(self, inputs):         
        x = self.flatten(inputs)   
        x = self.dense1(x)    
        output = self.dense2(x)     
        return output

In [3]:
X = tf.random.uniform((2, 20))
net = MLP()
net(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.04693116, -0.23327768, -0.30495134, -0.43888274,  0.40469113,
        -0.01286435, -0.12361967,  0.1569949 , -0.10138083,  0.11648329],
       [ 0.0966709 , -0.23705988, -0.20090276,  0.13870953,  0.07123503,
         0.13743114, -0.02035983,  0.17959478, -0.01121364,  0.02419421]],
      dtype=float32)>

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(256, activation=tf.nn.relu),
  tf.keras.layers.Dense(10),
])

model(X)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.00871513,  0.04244428, -0.06021744, -0.00070914, -0.00056697,
         0.13082618,  0.03810381,  0.02050602, -0.30404443, -0.4151866 ],
       [-0.1631701 , -0.16196717, -0.04597501,  0.04102934, -0.23793451,
        -0.09990399,  0.11620714, -0.19022998,  0.04731763,  0.06847502]],
      dtype=float32)>

In [6]:
class FancyMLP(tf.keras.Model):
  def __init__(self):
    super().__init__()
    self.flatten = tf.keras.layers.Flatten()
    self.rand_weight = tf.constant(
        tf.random.uniform((20, 20))
    )
    self.dense = tf.keras.layers.Dense(units=20, activation=tf.nn.relu)

  def call(self, inputs):
    x = self.flatten(inputs)
    x = tf.nn.relu(tf.matmul(x, self.rand_weight) + 1)
    x = self.dense(x)
    while tf.norm(x) > 1:
      x /= 2
    if tf.norm(x) < 0.8:
      x *= 10
    return tf.reduce_sum(x)

In [7]:
net = FancyMLP()
net(X)

<tf.Tensor: shape=(), dtype=float32, numpy=20.15387>

In [11]:
class NestMLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.net = tf.keras.Sequential()
        self.net.add(tf.keras.layers.Flatten())
        self.net.add(tf.keras.layers.Dense(64, activation=tf.nn.relu))
        self.net.add(tf.keras.layers.Dense(32, activation=tf.nn.relu))
        self.dense = tf.keras.layers.Dense(units=16, activation=tf.nn.relu)


    def call(self, inputs):         
        return self.dense(self.net(inputs))

net = tf.keras.Sequential()
net.add(NestMLP())
net.add(tf.keras.layers.Dense(20))
net.add(FancyMLP())

net(X)


<tf.Tensor: shape=(), dtype=float32, numpy=31.614838>

In [12]:
net = tf.keras.models.Sequential()
net.add(tf.keras.layers.Flatten())
net.add(tf.keras.layers.Dense(256, activation=tf.nn.relu))
net.add(tf.keras.layers.Dense(10))
X = tf.random.uniform((2, 20))
Y = net(X)
Y

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[-0.17282093,  0.14422745,  0.00898058, -0.0204713 ,  0.13752156,
         0.09560014, -0.19112042,  0.07976672, -0.1819982 ,  0.05444624],
       [-0.1534367 ,  0.03612772,  0.00209157,  0.11120219,  0.05699576,
        -0.0779936 , -0.16740409, -0.06558668, -0.02283833,  0.04169314]],
      dtype=float32)>

In [13]:
net.weights[0], type(net.weights[0])

(<tf.Variable 'dense_10/kernel:0' shape=(20, 256) dtype=float32, numpy=
 array([[ 0.11041021,  0.09746902, -0.05124407, ..., -0.06454624,
         -0.12543985,  0.08298469],
        [ 0.02063489, -0.08779754, -0.00265703, ..., -0.10874624,
         -0.03617434,  0.13276383],
        [ 0.082166  ,  0.01940548, -0.1252224 , ...,  0.02935354,
          0.06702505,  0.11504444],
        ...,
        [ 0.00690691, -0.07639812, -0.07794663, ...,  0.11588246,
          0.10227919, -0.05373617],
        [-0.07470477,  0.09868063,  0.02368638, ..., -0.09140637,
         -0.13551907,  0.02344511],
        [-0.07850659, -0.10579023, -0.04959231, ...,  0.13141069,
          0.14294717,  0.05671586]], dtype=float32)>,
 tensorflow.python.ops.resource_variable_ops.ResourceVariable)

In [16]:
class Linear(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.d1 = tf.keras.layers.Dense(
            units=10,
            activation=None,
            kernel_initializer=tf.random_normal_initializer(mean=0,stddev=0.01),
            bias_initializer=tf.zeros_initializer()
        )
        self.d2 = tf.keras.layers.Dense(
            units=1,
            activation=None,
            kernel_initializer=tf.ones_initializer(),
            bias_initializer=tf.ones_initializer()
        )

    def call(self, input):
        output = self.d1(input)
        output = self.d2(output)
        return output

net = Linear()
net(X)
net.get_weights()


[array([[-0.01038274, -0.00571152,  0.01534244, -0.01384987,  0.00458251,
          0.00245512, -0.00365852,  0.00596372, -0.01668887,  0.01229572],
        [ 0.00357784, -0.00802946,  0.01164066, -0.00431414, -0.00931946,
          0.00118658,  0.00747756, -0.00128287,  0.00267882,  0.00247838],
        [-0.01272422,  0.00630813, -0.00114123, -0.0085734 ,  0.01396967,
          0.00480525, -0.01302987,  0.00773505,  0.01556605, -0.00784679],
        [-0.01375213,  0.00839786, -0.00647823, -0.00624922, -0.00842024,
         -0.00074307,  0.0105812 , -0.02594885,  0.01524891,  0.01086135],
        [-0.01705718, -0.01944954,  0.01360267, -0.01110792,  0.00925118,
          0.0027647 ,  0.00489465,  0.01596266, -0.01005278,  0.0044206 ],
        [-0.01575712, -0.01011302,  0.00572893,  0.01911316,  0.0119338 ,
         -0.00769852, -0.00113736,  0.00041393, -0.00645461,  0.00620519],
        [ 0.00236708,  0.00955412,  0.00404336,  0.00115007,  0.00619473,
         -0.00271882,  0.0152997

In [18]:
def my_init():
    return tf.keras.initializers.Ones()

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(64, kernel_initializer=my_init()))

Y = model(X)
model.weights[0]


<tf.Variable 'dense_15/kernel:0' shape=(20, 64) dtype=float32, numpy=
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)>

In [21]:
class CenteredLayer(tf.keras.layers.Layer):
    def __init__(self):
        super().__init__()

    def call(self, inputs):
        return inputs - tf.reduce_mean(inputs)


In [22]:
layer = CenteredLayer()
layer(np.array([1, 2, 3, 4, 5]))


<tf.Tensor: shape=(5,), dtype=int64, numpy=array([-2, -1,  0,  1,  2])>

In [23]:
net = tf.keras.models.Sequential()
net.add(tf.keras.layers.Flatten())
net.add(tf.keras.layers.Dense(20))
net.add(CenteredLayer())
Y = net(X)
Y

<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
array([[ 0.5924619 , -1.2163553 ,  0.28532046,  0.4458469 ,  0.53974706,
        -0.14175072, -0.7032595 , -0.73925596,  0.3592776 , -0.42039463,
         0.2720846 , -0.5475589 ,  0.41600516,  0.05856604, -0.30693084,
         0.25809684,  0.30465284, -0.37964433, -0.52080506,  0.41890818],
       [ 0.43697998, -1.1213025 ,  0.8695245 ,  0.54326355,  0.43398744,
         0.05403411, -0.7499254 , -0.49776635,  0.4638942 , -0.04636384,
         0.62389153, -0.8496435 ,  0.7760295 , -0.22413445, -0.44606647,
         0.30393112,  0.4516574 , -0.27274373, -0.12636912,  0.40211   ]],
      dtype=float32)>

In [24]:
tf.reduce_mean(Y)

<tf.Tensor: shape=(), dtype=float32, numpy=1.7881394e-08>

In [28]:
class myDense(tf.keras.layers.Layer):
    def __init__(self, units):
        super().__init__()
        self.units = units

    def build(self, input_shape):     # 这里 input_shape 是第一次运行call()时参数inputs的形状
        self.w = self.add_weight(name='w',
            shape=[input_shape[-1], self.units], initializer=tf.random_normal_initializer())
        self.b = self.add_weight(name='b',
            shape=[self.units], initializer=tf.zeros_initializer())

    def call(self, inputs):
        y_pred = tf.matmul(inputs, self.w) + self.b
        return y_pred


In [29]:
dense = myDense(3)
dense(X)
dense.get_weights()

[array([[ 0.0069718 ,  0.04860806,  0.09158918],
        [-0.00436663, -0.01498434,  0.09659909],
        [ 0.00804838,  0.05808023,  0.00430054],
        [ 0.00243431,  0.00127583, -0.04561865],
        [ 0.04949647, -0.057792  , -0.03044767],
        [-0.0471512 ,  0.05894503,  0.00230876],
        [-0.05126056, -0.03171474, -0.03506846],
        [ 0.03053978,  0.06307156, -0.02951514],
        [ 0.11178696, -0.09383656,  0.06379426],
        [-0.0357197 , -0.06680331, -0.07077772],
        [-0.03302739,  0.02686972,  0.02948665],
        [-0.01119756, -0.03011241, -0.01160533],
        [ 0.0209505 ,  0.01499623,  0.02378532],
        [-0.00970662, -0.03041393, -0.0705054 ],
        [ 0.05350208, -0.02728941,  0.03297651],
        [ 0.08998615,  0.0633769 ,  0.00996308],
        [-0.0332689 , -0.04437619,  0.07433194],
        [ 0.05917949, -0.02663904,  0.00080485],
        [-0.02390481,  0.00727491, -0.01747975],
        [-0.05712789,  0.02635627, -0.01895631]], dtype=float32),
 ar

In [31]:
net = tf.keras.models.Sequential()
net.add(myDense(8))
net.add(myDense(1))

net(X)


<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.01174558],
       [0.01667943]], dtype=float32)>

In [33]:
x = tf.ones(3)
x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [34]:
np.save('x.npy', x)
x2 = np.load('x.npy')
x2

array([1., 1., 1.], dtype=float32)

In [36]:
y = tf.zeros(4)
np.save('xy.npy',[x,y])
x2, y2 = np.load('xy.npy', allow_pickle=True)
(x2, y2)


/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>)

In [37]:
mydict = {'x':x, 'y':y}
np.save('mydict.npy', mydict)
mydict2 = np.load('mydict.npy', allow_pickle=True)
mydict2


array({'x': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>, 'y': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>},
      dtype=object)