<a href="https://colab.research.google.com/github/joeytai/Machine-Learning/blob/main/dive_into_deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
x = tf.constant(range(12))
print(x.shape)

(12,)


In [3]:
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [5]:
x.shape     

TensorShape([12])

In [6]:
X = tf.reshape(x, (3,4)) 
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [10]:
tf.reshape(x, (-1, 4))
# same as tf.reshape(x, (3, -1))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [12]:
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [13]:
tf.ones((3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [49]:
#use list to set the init value of tensor
Y = tf.constant([[2, 1, 3, 4], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 3, 4],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)>

In [22]:
n = tf.random.normal(shape=[3, 4], mean=0, stddev=1)
n

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.71426564,  0.18349871,  0.05650334,  0.48187554],
       [-1.2151104 , -2.239919  ,  0.5478098 , -0.24144076],
       [-0.7523967 , -0.2770808 ,  1.859565  , -1.3081331 ]],
      dtype=float32)>

In [25]:
np.std(n)

1.0145584

In [26]:
X + Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  5,  7],
       [ 5,  7,  9, 11],
       [12, 12, 12, 12]], dtype=int32)>

In [27]:
X * Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  6, 12],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]], dtype=int32)>

In [28]:
X / Y

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[ 0.        ,  1.        ,  0.66666667,  0.75      ],
       [ 4.        ,  2.5       ,  2.        ,  1.75      ],
       [ 2.        ,  3.        ,  5.        , 11.        ]])>

In [44]:
Y = tf.cast(Y, tf.float32)
tf.exp(Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 7.389056 ,  2.7182817, 20.085537 , 54.59815  ],
       [ 2.7182817,  7.389056 , 20.085537 , 54.59815  ],
       [54.59815  , 20.085537 ,  7.389056 ,  2.7182817]], dtype=float32)>

In [31]:
Y = tf.cast(Y, tf.int32)
tf.matmul(X, tf.transpose(Y))

In [48]:
Y = tf.cast(Y, float32)
tf.concat([X,Y],axis = 0), tf.concat([X,Y],axis = 1)


NameError: ignored

In [50]:
tf.equal(X, Y)

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [51]:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=int32, numpy=66>

In [54]:
X = tf.cast(X, tf.float32)
tf.norm(X)

<tf.Tensor: shape=(), dtype=float32, numpy=22.494444>

In [56]:
A = tf.reshape(tf.constant(range(3)), (3, 1))
B = tf.reshape(tf.constant(range(2)), (1, 2))
A, B

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

In [57]:
print(A.shape)
print(B.shape)

(3, 1)
(1, 2)


In [59]:
A

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[0],
       [1],
       [2]], dtype=int32)>

In [60]:
B

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>

In [62]:
A + B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

In [64]:
X[1:3]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [65]:
X = tf.Variable(X)
X[1, 2].assign(9)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [66]:
X = tf.Variable(X)

In [68]:
X[1:2, :].assign(tf.ones(X[1:2, :].shape, dtype=tf.float32)*12)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [ ]:
X = tf.Variable(X)