In [2]:
import torch
import torch.nn.functional as F
# import torchvision
# import torchvision.transforms as transforms
# import sklearn.metrics as metrics

In [3]:
x = torch.Tensor(2, 3)
x

tensor([[0.0000e+00, 0.0000e+00, 1.8754e+28],
        [1.0396e-05, 2.0663e+20, 1.2926e-11]])

In [4]:
y = torch.Tensor(4, 2, 3)
y

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -1.0842e-19]],

        [[ 0.0000e+00, -1.0842e-19,  1.6816e-44],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [5]:
y.shape

torch.Size([4, 2, 3])

In [6]:
a = torch.rand(5, 3)
b = torch.rand(5, 3)
# option 1
# a + b
# option 2
# torch.add(a, b)
(a+b) == torch.add(a, b)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])